### ISSUE TITLE
Variable $version of type String! was provided invalid value

### ISSUE THREAD

**Issue by twsl** [WPMedia/delete-github-package-versions#6]
Im currently trying to delete a ruby gem package:
```
$ gem install packagename--version "0.0.1" --source "https://rubygems.pkg.github.com/twsl" 
```

```
- name: Delete GitHub Packages Versions
  uses: WPMedia/delete-github-package-versions@v0.4.10
  with:
    version: 0.0.1
    token: ${{secrets.GITHUB_TOKEN}}
    names: |
      packagename
```

But I do get the exception `Variable $version of type String! was provided invalid value`. What am I doing wrong?

Trying `semver-pattern: "=0.0.1"` doesn't result in deleting of said package.
